### ISSUE TITLE
你好请问表结构是如何定义的

### ISSUE THREAD

**Issue by feiyangbeyond** [MengxiQ/CMS#2]
你好，请问表结构是如何定义的？我没有在仓库中看到数据库表结构sql

**Comment by PPEQ** [comment]
给我留个你的联系方式，咱俩沟通一下来，作者联系不上啊

**Comment by feiyangbeyond** [comment]
> 给我留个你的联系方式，咱俩沟通一下来，作者联系不上啊

发下qq，我加你

**Comment by PPEQ** [comment]
11730138QQ
13330433523微信



***@***.***
 
发件人： Ryan
发送时间： 2024-06-04 09:20
收件人： MengxiQ/CMS
抄送： PPEQ; Comment
主题： Re: [MengxiQ/CMS] 你好请问表结构是如何定义的 (Issue #2)
给我留个你的联系方式，咱俩沟通一下来，作者联系不上啊
发下qq，我加你

**Comment by MengxiQ** [comment]
> 你好，请问表结构是如何定义的？我没有在仓库中看到数据库表结构sql
目录/backend/CMS/Database/20210502181012.nb3
用Navicat备份还原

**Comment by zanzan66** [comment]
你好请问您的python和django版本是多少

**Comment by feiyangbeyond** [comment]
> 你好请问您的python和django版本是多少

python版本是3.8，Django版本忘记了（不能用最新版，最新的版本有些api被移除了），可以尝试搜索下和问下ai
